# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-20 18:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cah', '0002_board'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='cur_player',
            new_name='cur_judge',
        ),
    ]
