# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-02 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cah', '0003_auto_20170120_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='card_pool',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='board',
            name='cur_card',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='player',
            name='cards',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='player',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
