# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-02 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cah', '0004_auto_20170202_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='board',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cah.Board'),
        ),
    ]
