# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-02 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cah', '0006_auto_20170202_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='card_pool',
            new_name='black_card_pool',
        ),
        migrations.AddField(
            model_name='board',
            name='white_card_pool',
            field=models.TextField(default='[]'),
        ),
    ]
