# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-02 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cah', '0007_auto_20170202_1732'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlackCards',
            new_name='BlackCard',
        ),
    ]
