# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-02 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cah', '0008_auto_20170202_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='takes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
